{% set name = "binapy" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/binapy-{{ version }}.tar.gz
  sha256: 570c5098d42f037ffb3d2e563998f3cff69ad25ca1f43f9c3815432dccd08233

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - poetry-core >=1.0.0
    - typing-extensions >=4.3.0

test:
  imports:
    - binapy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/guillp/binapy
  doc_url: https://guillp.github.io/binapy/
  summary: Binary Data manipulation, for humans.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
